apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdataconsole
  name: likeminds-pingdataconsole
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdataconsole