apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdirectoryproxy
  name: likeminds-pingdirectoryproxy
spec:
  ports:
  - name: https
    port: 1443
    protocol: TCP
    targetPort: 1443
  - name: ldaps
    port: 1636
    protocol: TCP
    targetPort: 1636
  selector:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdirectoryproxy
  type: LoadBalancer