kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ping-directory
- ping-dataconsole
- ping-datasync
#- pingfederate-admin
#- pingfederate-engine
#- ping-delegator
- global-env.yaml